### ISSUE TITLE
Test for Django 1.10, 1.11 & Python 3.5, 3.6

### ISSUE THREAD

**Issue by Bartvds** [jsatt/django-db-email-backend#2]
For a development tool it doesn't matter too much but maybe it could be cool to bump some test versions if you publish #1?

**Comment by jsatt** [comment]
@Bartvds, thanks for the help. 

I had a little free time this morning, so I updated to support Django 1.10, will add 1.11 to tox build after it's officially released. Everything is working fine locally on Python 3.5, but Travis complained when I tried to use it in the tests with it. I'll see about updating in the future.

These changes and your PR are now published as version 0.3.

**Comment by Bartvds** [comment]
@jsatt Cool, it is nice to stay fresh.

Thanks for publishing so quickly! :+1:
